from __future__ import annotations

import sys
from pathlib import Path

from check_entry import COMMUNITY_DIR, discover_entries
from entry_rules import load_meta

_HEADER = """\
# Community

<!-- This file is generated by community/scripts/build_index.py. Do not edit by hand. -->

Work built with Opik by the open-source community. These entries are
**community-contributed and not maintainer-verified** — they are showcased here
to help people discover what others are building. Standout, real-world projects
are hosted in-repo (see the Hosted column).

To add your own, see [CONTRIBUTING.md](CONTRIBUTING.md).
"""

_TABLE_HEADER = (
    "| Project | Author | Description | Platform | Links | Hosted | Tags |\n"
    "|---|---|---|---|---|---|---|"
)


def load_entries(community_dir: Path) -> list[dict]:
    entries: list[dict] = []
    for entry in discover_entries(community_dir):
        data, errors = load_meta(entry)
        if errors:
            continue
        entries.append(
            {
                "slug": entry.name,
                "title": str(data.get("title", entry.name)),
                "description": str(data.get("description", "")),
                "author": str(data.get("author", "")),
                "links": data.get("links") or {},
                "opik_platform": str(data.get("opik_platform", "")),
                "tags": data.get("tags") or [],
                "hosted": bool(data.get("hosted", False)),
            }
        )
    entries.sort(key=lambda e: e["title"].casefold())
    return entries


def _escape_pipes(value: str) -> str:
    return value.replace("|", "\\|")


def _links_cell(links: dict) -> str:
    parts = [
        f"[{_escape_pipes(str(label))}]({_escape_pipes(str(url))})"
        for label, url in links.items()
        if str(url).startswith("http")
    ]
    return "<br>".join(parts) if parts else ""


def _row(entry: dict) -> str:
    project = f"[{_escape_pipes(entry['title'])}]({entry['slug']}/)"
    author = (
        f"[@{_escape_pipes(entry['author'])}](https://github.com/{_escape_pipes(entry['author'])})"
        if entry["author"]
        else ""
    )
    tags = _escape_pipes(", ".join(str(t) for t in entry["tags"]))
    hosted = "hosted" if entry["hosted"] else ""
    cells = [
        project,
        author,
        _escape_pipes(entry["description"]),
        _escape_pipes(entry["opik_platform"]),
        _links_cell(entry["links"]),
        hosted,
        tags,
    ]
    return "| " + " | ".join(cells) + " |"


def render_index(entries: list[dict]) -> str:
    lines = [_HEADER]
    if not entries:
        lines.append("_No community contributions yet — be the first!_\n")
    else:
        lines.append(_TABLE_HEADER)
        lines.extend(_row(e) for e in entries)
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def write_index(community_dir: Path) -> None:
    (community_dir / "README.md").write_text(
        render_index(load_entries(community_dir)), encoding="utf-8"
    )


def check_index(community_dir: Path) -> bool:
    readme = community_dir / "README.md"
    current = readme.read_text(encoding="utf-8") if readme.is_file() else ""
    return current == render_index(load_entries(community_dir))


def main(argv: list[str] | None = None) -> int:
    args = sys.argv[1:] if argv is None else argv
    if "--check" in args:
        if check_index(COMMUNITY_DIR):
            print("community/README.md is up to date.")
            return 0
        print("community/README.md is stale. Run: python build_index.py")
        return 1
    write_index(COMMUNITY_DIR)
    print("Wrote community/README.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
