from __future__ import annotations

import sys
from pathlib import Path

from project_rules import load_projects, validate_projects

COMMUNITY_DIR = Path(__file__).resolve().parent.parent
PROJECTS_FILE_NAME = "projects.yaml"

_HEADER = """\
# Community

<!-- This file is generated by community/_ci/build_index.py. Do not edit by hand. -->

A curated index of projects the open-source community has built with Opik. It is
links-only: each project lives in its author's repository, and entries are
**community-contributed and not maintainer-verified** — they are showcased here
to help people discover what others are building.

To add yours, see [CONTRIBUTING.md](CONTRIBUTING.md) — it's one small block in
[projects.yaml](projects.yaml).
"""

_TABLE_HEADER = "| Project | Description | Author |\n|---|---|---|"


def load_entries(community_dir: Path) -> list[dict]:
    projects, errors = load_projects(community_dir / PROJECTS_FILE_NAME)
    if not errors:
        errors = validate_projects(projects)
    if errors:
        raise ValueError("invalid projects.yaml: " + "; ".join(errors))

    entries = [
        {
            "title": str(item["title"]).strip(),
            "description": str(item["description"]).strip(),
            "author": str(item["author"]).strip(),
            "repo": str(item["repo"]).strip(),
        }
        for item in projects
    ]
    entries.sort(key=lambda e: e["title"].casefold())
    return entries


def _escape_pipes(value: str) -> str:
    return value.replace("|", "\\|")


def _row(entry: dict) -> str:
    project = f"[{_escape_pipes(entry['title'])}]({_escape_pipes(entry['repo'])})"
    author = (
        f"[@{_escape_pipes(entry['author'])}](https://github.com/{_escape_pipes(entry['author'])})"
    )
    cells = [project, _escape_pipes(entry["description"]), author]
    return "| " + " | ".join(cells) + " |"


def render_index(entries: list[dict]) -> str:
    lines = [_HEADER]
    if not entries:
        lines.append("_No community contributions yet — be the first!_\n")
    else:
        lines.append(_TABLE_HEADER)
        lines.extend(_row(e) for e in entries)
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def write_index(community_dir: Path) -> None:
    (community_dir / "README.md").write_text(
        render_index(load_entries(community_dir)), encoding="utf-8"
    )


def check_index(community_dir: Path) -> bool:
    readme = community_dir / "README.md"
    current = readme.read_text(encoding="utf-8") if readme.is_file() else ""
    return current == render_index(load_entries(community_dir))


def main(argv: list[str] | None = None) -> int:
    args = sys.argv[1:] if argv is None else argv
    try:
        if "--check" in args:
            if check_index(COMMUNITY_DIR):
                print("community/README.md is up to date.")
                return 0
            print("community/README.md is stale. Run: python build_index.py")
            return 1
        write_index(COMMUNITY_DIR)
    except ValueError as exc:
        print(f"Cannot build index: {exc}")
        return 1
    print("Wrote community/README.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
